### ISSUE TITLE
Multiple decode errors occured: Try checking the baud rate and XTAL frequency setting in menuconfig

### ISSUE THREAD

**Issue by huangdiajd** [nopnop2002/esp-idf-m5stickC#4]
Multiple decode errors occured: Try checking the baud rate and XTAL frequency setting in menuconfig
�k�E���0x00,\E���0x00,dߖ��0��,cs�E����0,h�E���0�0,wpߖ��0��
moV�"%=� cloc�"���2C!녑�0x3ff�30,���70�j
ho�╗tail�2 ro�
              �j
Multiple decode errors occured: Try checking the baud rate and XTAL frequency setting in menuconfig
�+��0�����,len�����j
ho 0������&�����4
Multiple decode errors occured: Try checking the baud rate and XTAL frequency setting in menuconfig
�Y���0x4008�4c

Hello, how do I configure my ST7735S screen to eliminate this warning

**Comment by nopnop2002** [comment]
Try idf.py flash -b 115200 monitor

**Comment by nopnop2002** [comment]
I've never seen this error before.
